### ISSUE TITLE
Classe Vetor

### ISSUE THREAD

**Issue by luiz-reis** [luiz-reis/pg-corte-plano#1]
Implementar classe vetor, com métodos sobre as operações básicas sobre vetor. 
- [x] Norma
- [x] Normalizar
- [x] Soma
- [x] Multiplicação por escalar
- [x] Produto vetorial
- [x] Produto Interno

**Comment by rcalegario** [comment]
@luiz-reis cria a classe e da o push dela, por favor

**Comment by luiz-reis** [comment]
blz, já faço isso
